
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.79.46.8:3306/storage?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: storage
    password: 0803x
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

mybatis-plus:
  #配置驼峰命名法
  configLocation: #此处不能用局部configuration变量来配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/storage/mapper/xml/*.xml
  type-aliases-package: com.storage.pojo