
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://120.79.46.8:3306/storage?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: storage
    password: 0803x
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
